/* Log of translation statistics v1.2 */

ModelManagement.Check.Translation.TranslationStatistics_v_1_2(336, 4685, 103, 1888,
   2694, 152, 1643, 1291, 1032, 659, 708, 0, 2, 63, 1184, 1345, 0, 0, {108, 24, 4,
   4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4}, {20, 0, 2, 2, 2, 2,
   2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2}, fill(0,0), fill(0,0), 0, 0, 
  fill(0,0), fill(0,0), fill(0,0), fill(0,0), 0, {"63_states", "condenser.junctionN.inlets[10].m_flow",
   "condenser.junctionN.inlets[11].m_flow", "condenser.junctionN.inlets[12].m_flow",
   "condenser.junctionN.inlets[13].m_flow", "condenser.junctionN.inlets[14].m_flow",
   "condenser.junctionN.inlets[15].m_flow", "condenser.junctionN.inlets[16].m_flow",
   "condenser.junctionN.inlets[17].m_flow", "condenser.junctionN.inlets[18].m_flow",
   "condenser.junctionN.inlets[19].m_flow", "condenser.junctionN.inlets[20].m_flow",
   "condenser.junctionN.inlets[2].m_flow", "condenser.junctionN.inlets[3].m_flow",
   "condenser.junctionN.inlets[4].m_flow", "condenser.junctionN.inlets[5].m_flow",
   "condenser.junctionN.inlets[6].m_flow", "condenser.junctionN.inlets[7].m_flow",
   "condenser.junctionN.inlets[8].m_flow", "condenser.junctionN.inlets[9].m_flow",
   "condenser.thermalElementA[10].h", "condenser.thermalElementA[11].h", 
  "condenser.thermalElementA[12].h", "condenser.thermalElementA[13].h", 
  "condenser.thermalElementA[14].h", "condenser.thermalElementA[15].h", 
  "condenser.thermalElementA[16].h", "condenser.thermalElementA[17].h", 
  "condenser.thermalElementA[18].h", "condenser.thermalElementA[19].h", 
  "condenser.thermalElementA[1].h", "condenser.thermalElementA[20].h", 
  "condenser.thermalElementA[2].h", "condenser.thermalElementA[3].h", 
  "condenser.thermalElementA[4].h", "condenser.thermalElementA[5].h", 
  "condenser.thermalElementA[6].h", "condenser.thermalElementA[7].h", 
  "condenser.thermalElementA[8].h", "condenser.thermalElementA[9].h", 
  "condenser.thermalElementB[10].h", "condenser.thermalElementB[11].h", 
  "condenser.thermalElementB[12].h", "condenser.thermalElementB[13].h", 
  "condenser.thermalElementB[14].h", "condenser.thermalElementB[15].h", 
  "condenser.thermalElementB[16].h", "condenser.thermalElementB[17].h", 
  "condenser.thermalElementB[18].h", "condenser.thermalElementB[19].h", 
  "condenser.thermalElementB[1].h", "condenser.thermalElementB[20].h", 
  "condenser.thermalElementB[2].h", "condenser.thermalElementB[3].h", 
  "condenser.thermalElementB[4].h", "condenser.thermalElementB[5].h", 
  "condenser.thermalElementB[6].h", "condenser.thermalElementB[7].h", 
  "condenser.thermalElementB[8].h", "condenser.thermalElementB[9].h", 
  "mCV.dp_int", "mCV1.dp_int", "sinkA.inlet.m_flow", "sourceB.outlet.m_flow"}, 
  fill("", 0), fill("", 0), fill("", 0), fill(0.0, 0),      0.000, fill(0, 0), 0)
